// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraingAssistantDAL.DataAccess;

#nullable disable

namespace TraingAssistantDAL.Migrations
{
    [DbContext(typeof(TrainingAssistantContext))]
    [Migration("20230402163156_DataChange")]
    partial class DataChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TraingAssistantDAL.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BurnedKcal")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BurnedKcal = 0.0,
                            Name = "Bench press",
                            Time = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            BurnedKcal = 0.0,
                            Name = "Squat",
                            Time = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            BurnedKcal = 0.0,
                            Name = "Deadlift",
                            Time = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("TraingAssistantDAL.Models.ExerciseMusclePart", b =>
                {
                    b.Property<int>("ExercisesId")
                        .HasColumnType("int");

                    b.Property<int>("MusclePartsId")
                        .HasColumnType("int");

                    b.HasKey("ExercisesId", "MusclePartsId");

                    b.HasIndex("MusclePartsId");

                    b.ToTable("ExerciseMuscleParts");

                    b.HasData(
                        new
                        {
                            ExercisesId = 1,
                            MusclePartsId = 1
                        },
                        new
                        {
                            ExercisesId = 1,
                            MusclePartsId = 3
                        },
                        new
                        {
                            ExercisesId = 2,
                            MusclePartsId = 2
                        },
                        new
                        {
                            ExercisesId = 2,
                            MusclePartsId = 3
                        },
                        new
                        {
                            ExercisesId = 3,
                            MusclePartsId = 3
                        });
                });

            modelBuilder.Entity("TraingAssistantDAL.Models.MusclePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Legs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Back"
                        });
                });

            modelBuilder.Entity("TraingAssistantDAL.Models.ExerciseMusclePart", b =>
                {
                    b.HasOne("TraingAssistantDAL.Models.Exercise", "Exercise")
                        .WithMany("ExercisesMuscleParts")
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraingAssistantDAL.Models.MusclePart", "MusclePart")
                        .WithMany("ExercisesMuscleParts")
                        .HasForeignKey("MusclePartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MusclePart");
                });

            modelBuilder.Entity("TraingAssistantDAL.Models.Exercise", b =>
                {
                    b.Navigation("ExercisesMuscleParts");
                });

            modelBuilder.Entity("TraingAssistantDAL.Models.MusclePart", b =>
                {
                    b.Navigation("ExercisesMuscleParts");
                });
#pragma warning restore 612, 618
        }
    }
}
